web:
  image: ritsse/teamroomfrontend
  ports:
    - 80:80
    - 443:443
  links:
    - back

back:
  image: ritsse/teamroombackend

watch:
  image: centurylink/watchtower
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock

