version: '2'
services:
  web:
    image: ritsse/teamroomfrontend
    links:
      - back
    ports:
      - 80:80

  back:
    image: ritsse/teamroombackend

  watch:
    image: centurylink/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

